apiVersion: v1
kind: Secret
metadata:
  name: vitalsync-secret
type: Opaque
data:
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQxMjM=  
  POSTGRES_USER: dml0YWxzeW5jX3VzZXI=      
  POSTGRES_DB: dml0YWxzeW5j               